title: networking, scuba diving, and other things.
description: get networky
disqus_shortname: aaronbradshaw
share: true

# Blog URLs
url: "http://aaronbradshaw.com" # the base hostname & protocol for your site
production_url: aaronbradshaw.com

# Owner/author information
owner:
  name: Aaron Bradshaw
  avatar: avatar.png
  email: aaronbradshaw.blog@mailnull.com

  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description: Network Engineer for Cisco.  I enjoy networking, scuba diving, sailing, and great bourbon.  This is a personal blog, thoughts are my own.

  # Social networking links used in footer. Update and remove as you like.
  github: aaronbradshaw
  twitter: aaronbradshaw
  facebook: aaronbradshaw
  linkedin: aaronbradshaw

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured
    url: /featured
  - title: Categories
    url: /categories
  - title: Archive
    url: /archive
  - title: Tags
    url: /tags
  - title: Dive Log
    url: /divelog.html
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New York
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# http://jekyllrb.com/docs/permalinks/
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  input: GFM
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Use GitHub Pages Sitemap!
# https://github.com/jekyll/jekyll-sitemap
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

exclude: ["Gemfile", "Gemfile.lock", "Rakefile", ".rbenv-version", "README.md"]
